"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "id";

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.works": "Works",
    "nav.skills": "Skills",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.cta": "Let's talk",

    // Hero
    "hero.eyebrow": "UI/UX Designer · Bandung, Indonesia",
    "hero.heading1": "Crafting digital",
    "hero.heading2": "experiences",
    "hero.heading3": "people love.",
    "hero.desc": "I design digital products that are useful, intuitive, and enjoyable — backed by UX laws, user research, and meticulous attention to detail.",
    "hero.cta.work": "See my work",
    "hero.cta.about": "About me",
    "hero.stat1.label": "Years of experience",
    "hero.stat1.value": "3+",
    "hero.stat2.label": "Instagram followers",
    "hero.stat2.value": "500K+",
    "hero.stat3.label": "Total community",
    "hero.stat3.value": "1.2M+",
    "hero.find": "Find me on",
    "hero.scroll": "Scroll to explore",

    // Projects
    "projects.eyebrow": "Selected work",
    "projects.heading": "Recent projects",
    "projects.all": "All projects",
    "projects.featured": "Featured",

    // Skills
    "skills.eyebrow": "Toolkit",
    "skills.heading": "Skills & tools",

    // About
    "about.eyebrow": "About",
    "about.p1": "A UI/UX Designer from Bandung, Indonesia with 3+ years of experience crafting digital products that are both useful and enjoyable. I work with teams to translate user needs into beautiful, functional interfaces.",
    "about.p2": "Beyond client work, I share design knowledge and insights with a community of 1.2M+ followers across social media — making design more accessible and understandable for everyone.",
    "about.highlights": "Highlights",
    "about.stat1": "Years",
    "about.stat2": "Projects",
    "about.stat3": "Community",
    "about.philosophy.label": "Design philosophy",
    "about.philosophy.quote": "\"Great design is invisible. It solves the right problem in the simplest way — making the user feel understood, not impressed.\"",
    "about.item1.title": "Based in Bandung, Indonesia",
    "about.item1.desc": "Available for remote work worldwide",
    "about.item2.title": "3+ Years of Experience",
    "about.item2.desc": "Working across startups to enterprise clients",
    "about.item3.title": "UX-First Approach",
    "about.item3.desc": "Every decision backed by research & UX laws",
    "about.item4.title": "1.2M+ Community",
    "about.item4.desc": "Design educator across Instagram, Threads & TikTok",

    // Contact
    "contact.eyebrow": "Let's collaborate",
    "contact.heading1": "Have a project",
    "contact.heading2": "in",
    "contact.heading3": "mind?",
    "contact.desc": "Let's create something great together.",
    "contact.desc2": "I'm currently available for new projects.",

    // Portfolio detail
    "portfolio.back":                   "Back to portfolio",
    "portfolio.meta.year":              "Year",
    "portfolio.meta.duration":          "Duration",
    "portfolio.meta.role":              "Role",
    "portfolio.meta.client":            "Client",
    "portfolio.context.flow":           "The main product flow includes:",
    "portfolio.problem.preview":        "Preview",
    "portfolio.notion.button":          "Read Full Case Study",
    "portfolio.sidebar.title":          "On this page",
    "portfolio.sidebar.backtop":        "Back to top",
    "portfolio.reflection.collabTitle": "Shoutout to all collaborators",
    "portfolio.reflection.collabDesc":  "Huge shoutout to everyone I collaborated with during this project",
    "portfolio.cta.label":              "Next step",
    "portfolio.cta.heading":            "Want to see the full case study?",
    "portfolio.cta.live":               "Live Site",
    "portfolio.cta.notion":             "View on Notion",
    "portfolio.cta.all":                "All projects",

    // Login
    "login.subtitle": "Sign in to manage dashboard",
    "login.username.ph": "Enter username",
    "login.password.ph": "Enter password",
    "login.remember": "Remember me",
    "login.remember.desc": "Stay signed in for 30 days",
    "login.submit": "Sign in",
    "login.loading": "Verifying…",
    "login.success": "Signed in",
    "login.footer": "Without 'remember me', session ends in",
    "login.footer.duration": "8 hours",
    "login.error.default": "Incorrect username or password.",
    "login.error.network": "Connection failed. Check your network and try again.",

    // Dashboard common
    "dash.refresh": "Refresh",
    "dash.subtitle": "Analytics and content management",
    "dash.analytics": "Analytics",
    "dash.chart.hover": "Hover point for details",
    "dash.chart.total": "Total",
    "dash.chart.avg": "Average:",
    "dash.chart.peak": "Peak:",
    "dash.chart.perday": "/ day",
    "dash.chart.nodata": "Run SQL migration to activate analytics",
    "dash.export.csv": "Export CSV",
    "dash.export.json": "Export JSON",
    "dash.toppages": "Top Pages",
    "dash.toppages.sub": "last 7 days",
    "dash.stat.today": "Today",
    "dash.stat.week": "7 Days",
    "dash.stat.projects": "Projects",
    "dash.stat.portfolio": "Total portfolio",
    "dash.stat.top": "Top:",
    "dash.filter.7d": "7 Days",
    "dash.filter.14d": "14 Days",
    "dash.filter.30d": "30 Days",
    "dash.time.justnow": "just now",
    "dash.time.minsago": "min ago",
    "dash.time.hrsago": "hr ago",
    "dash.time.daysago": "d ago",
    "dash.confirm.delete": "Delete \"{title}\"? This action cannot be undone.",
    "dash.deleting": "Deleting...",
    "dash.portfolio.section": "Portfolio",
    "dash.portfolio.add": "Add Project",
    "dash.portfolio.subtitle": "Manage all portfolio projects",
    "dash.portfolio.empty.title": "No projects yet",
    "dash.portfolio.empty.desc": "Add your first project",
    "dash.portfolio.col.title": "Title",
    "dash.portfolio.col.type": "Type",
    "dash.portfolio.col.year": "Year",
    "dash.portfolio.col.actions": "Actions",
    "dash.portfolio.export": "Export Projects",
    "dash.portfolio.view": "View page",

    // Settings
    "dash.settings.title": "Settings",
    "dash.settings.subtitle": "Manage credentials and login sessions",
    "dash.settings.account": "Active Account",
    "dash.settings.form.title": "Update Credentials",
    "dash.settings.form.desc": "Change username and password. You will be logged out after saving.",
    "dash.settings.current.pw": "Current Password",
    "dash.settings.new.username": "New Username",
    "dash.settings.new.pw": "New Password",
    "dash.settings.confirm.pw": "Confirm Password",
    "dash.settings.save": "Save Changes",
    "dash.settings.saving": "Saving…",
    "dash.settings.saved": "Saved — redirecting to login…",
    "dash.settings.err.username": "Username must be at least 3 characters.",
    "dash.settings.err.pwlen": "New password must be at least 4 characters.",
    "dash.settings.err.pwmatch": "Passwords do not match.",
    "dash.settings.err.network": "Connection failed. Try again.",
    "dash.settings.sessions": "Active Login Sessions",
    "dash.settings.sessions.revoke": "Revoke",
    "dash.settings.sessions.revoke.all": "Revoke {n} other sessions",
    "dash.settings.sessions.none": "No active sessions found.",
    "dash.settings.sessions.current": "This session",
    "dash.settings.sessions.footer": "Revoked sessions will be logged out on next request.",
    "dash.settings.sessions.expired": "expired",
    "dash.settings.sessions.expiry.days": "expires in {d}d {h}h",
    "dash.settings.sessions.expiry.hrs": "expires in {h}h",
    "dash.settings.sessions.login": "Login",
    "dash.settings.pw.weak": "Weak",
    "dash.settings.pw.fair": "Fair",
    "dash.settings.pw.strong": "Strong",
    "dash.settings.pw.vstrong": "Very Strong",

    // Sidenav
    "dash.nav.dashboard":   "Dashboard",
    "dash.nav.portfolio":   "Portfolio",
    "dash.nav.settings":    "Settings",
    "dash.sidenav.viewsite":  "View Site",
    "dash.sidenav.lightmode": "Light Mode",
    "dash.sidenav.darkmode":  "Dark Mode",
    "dash.sidenav.language":  "Language",
    "dash.sidenav.logout":    "Logout",
    "dash.sidenav.admin":     "Administrator",
    "dash.sidenav.expand":    "Expand sidebar",
    "dash.sidenav.collapse":  "Collapse sidebar",

    // Stat / chart extras
    "dash.stat.totalviews":    "Total Views",
    "dash.chart.updated":      "Updated",
    "dash.novisit":            "No visit data yet",

    // Actions
    "dash.actions.edit":    "Edit",
    "dash.actions.delete":  "Delete",
    "dash.portfolio.manage": "Manage",

    // ProjectForm — section type labels
    "form.stype.nutshell":          "In a Nutshell",
    "form.stype.context":           "Context",
    "form.stype.problem-discovery": "Problem Discovery",
    "form.stype.problem":           "Problem",
    "form.stype.solution":          "Solution",
    "form.stype.finaldesign":       "Final Design",
    "form.stype.reflection":        "Reflection",
    "form.stype.notion-only":       "Notion Only",

    // ProjectForm — UI strings
    "form.untitled":              "Untitled",
    "form.section.type":          "Section Type",
    "form.section.content":       "Content / Body Text",
    "form.section.image":         "Image (path)",
    "form.section.image.hint":    "Example: /Aitiserve_Context.jpg",
    "form.section.boldlist":      "Bold List (Context)",
    "form.section.add.item":      "Add Item",
    "form.section.design.items":  "Design Items (label + image)",
    "form.section.add.image":     "Add Image",
    "form.section.learnings":     "Learnings (one per line)",
    "form.section.collabs":       "Collaborators (one per line)",
    "form.section.add":           "Add Section",
    "form.section.empty":         "No sections yet. Add the first section.",

    "form.add.title":             "Add New Project",
    "form.edit.prefix":           "Edit:",
    "form.add.hint":              "Fill all fields then save",
    "form.saved":                 "✓ Saved",
    "form.view":                  "View →",
    "form.saving":                "Saving…",
    "form.save":                  "Save",
    "form.err.save":              "An error occurred while saving.",
    "form.err.network":           "Connection failed. Try again.",

    "form.card.identity":         "Project Identity",
    "form.card.sections":         "Sections",
    "form.card.details":          "Project Details",
    "form.card.tags":             "Tags & Skills",
    "form.card.visual":           "Visual & Links",

    "form.field.id":              "ID (unique slug)",
    "form.field.id.hint.new":     "Auto-generated from title",
    "form.field.id.hint.edit":    "Cannot be changed after saving",
    "form.field.type":            "Type",
    "form.field.title":           "Title",
    "form.field.desc":            "Short Description",
    "form.field.year":            "Year",
    "form.field.duration":        "Duration",
    "form.field.role":            "Role",
    "form.field.client":          "Client",
    "form.field.tags":            "Tags",
    "form.field.skills":          "Skills",
    "form.field.comma.hint":      "Separate with commas",
    "form.field.bg.color":        "Background Color (hex)",
    "form.field.accent.color":    "Accent Color (hex)",
    "form.field.thumbnail":       "Thumbnail",
    "form.field.thumbnail.hint":  "Path from /public",
    "form.field.liveurl":         "Live URL",
    "form.field.external":        "External Link (Notion)",
    "form.field.label.nav":       "Label (sidebar nav)",
    "form.field.heading":         "Heading",

    "form.ph.title":              "Project title...",
    "form.ph.desc":               "Brief project description...",
    "form.ph.section.content":    "Section body text...",
    "form.ph.desc.item":          "Description",
    "form.ph.learnings":          "One point per line...",
  },
  id: {
    // Navbar
    "nav.works": "Karya",
    "nav.skills": "Keahlian",
    "nav.about": "Tentang",
    "nav.contact": "Kontak",
    "nav.cta": "Hubungi",

    // Hero
    "hero.eyebrow": "Desainer UI/UX · Bandung, Indonesia",
    "hero.heading1": "Merancang pengalaman",
    "hero.heading2": "digital",
    "hero.heading3": "yang dicintai.",
    "hero.desc": "Saya mendesain produk digital yang berguna, intuitif, dan menyenangkan — didukung UX laws, riset pengguna, dan perhatian penuh terhadap detail.",
    "hero.cta.work": "Lihat karya",
    "hero.cta.about": "Tentang saya",
    "hero.stat1.label": "Tahun pengalaman",
    "hero.stat1.value": "3+",
    "hero.stat2.label": "Followers Instagram",
    "hero.stat2.value": "500K+",
    "hero.stat3.label": "Total komunitas",
    "hero.stat3.value": "1.2M+",
    "hero.find": "Temukan saya di",
    "hero.scroll": "Scroll untuk jelajahi",

    // Projects
    "projects.eyebrow": "Karya pilihan",
    "projects.heading": "Proyek terbaru",
    "projects.all": "Semua proyek",
    "projects.featured": "Unggulan",

    // Skills
    "skills.eyebrow": "Keahlian",
    "skills.heading": "Skill & tools",

    // About
    "about.eyebrow": "Tentang",
    "about.p1": "Desainer UI/UX dari Bandung, Indonesia dengan 3+ tahun pengalaman merancang produk digital yang bermanfaat dan menyenangkan. Saya bekerja bersama tim untuk menerjemahkan kebutuhan pengguna menjadi antarmuka yang indah dan fungsional.",
    "about.p2": "Di luar pekerjaan klien, saya berbagi pengetahuan dan wawasan desain kepada komunitas 1,2 juta+ pengikut di media sosial — menjadikan desain lebih mudah diakses dan dipahami oleh semua orang.",
    "about.highlights": "Pencapaian",
    "about.stat1": "Tahun",
    "about.stat2": "Proyek",
    "about.stat3": "Komunitas",
    "about.philosophy.label": "Filosofi desain",
    "about.philosophy.quote": "\"Desain yang baik tidak terlihat. Ia memecahkan masalah yang tepat dengan cara paling sederhana — membuat pengguna merasa dipahami, bukan terkesan.\"",
    "about.item1.title": "Berbasis di Bandung, Indonesia",
    "about.item1.desc": "Tersedia untuk kerja jarak jauh",
    "about.item2.title": "3+ Tahun Pengalaman",
    "about.item2.desc": "Bekerja dari startup hingga perusahaan enterprise",
    "about.item3.title": "Pendekatan UX-First",
    "about.item3.desc": "Setiap keputusan didukung riset & UX laws",
    "about.item4.title": "Komunitas 1,2 Juta+",
    "about.item4.desc": "Edukator desain di Instagram, Threads & TikTok",

    // Contact
    "contact.eyebrow": "Ayo berkolaborasi",
    "contact.heading1": "Punya proyek",
    "contact.heading2": "di",
    "contact.heading3": "pikiran?",
    "contact.desc": "Mari buat sesuatu yang luar biasa bersama.",
    "contact.desc2": "Saya saat ini tersedia untuk proyek baru.",

    // Portfolio detail
    "portfolio.back":                   "Kembali ke portofolio",
    "portfolio.meta.year":              "Tahun",
    "portfolio.meta.duration":          "Durasi",
    "portfolio.meta.role":              "Peran",
    "portfolio.meta.client":            "Klien",
    "portfolio.context.flow":           "Alur produk utama meliputi:",
    "portfolio.problem.preview":        "Pratinjau",
    "portfolio.notion.button":          "Baca Case Study Lengkap",
    "portfolio.sidebar.title":          "Di halaman ini",
    "portfolio.sidebar.backtop":        "Kembali ke atas",
    "portfolio.reflection.collabTitle": "Terima kasih kepada semua kolaborator",
    "portfolio.reflection.collabDesc":  "Terima kasih besar kepada semua yang berkolaborasi dalam proyek ini",
    "portfolio.cta.label":              "Langkah selanjutnya",
    "portfolio.cta.heading":            "Ingin melihat case study lengkap?",
    "portfolio.cta.live":               "Situs Langsung",
    "portfolio.cta.notion":             "Lihat di Notion",
    "portfolio.cta.all":                "Semua proyek",

    // Login
    "login.subtitle": "Masuk untuk mengelola dashboard",
    "login.username.ph": "Masukkan username",
    "login.password.ph": "Masukkan password",
    "login.remember": "Ingat saya",
    "login.remember.desc": "Tetap masuk selama 30 hari",
    "login.submit": "Masuk",
    "login.loading": "Memverifikasi…",
    "login.success": "Berhasil masuk",
    "login.footer": "Tanpa 'ingat saya' sesi berakhir dalam",
    "login.footer.duration": "8 jam",
    "login.error.default": "Username atau password salah.",
    "login.error.network": "Koneksi gagal. Periksa jaringan dan coba lagi.",

    // Dashboard common
    "dash.refresh": "Refresh",
    "dash.subtitle": "Statistik dan manajemen konten",
    "dash.analytics": "Analitik",
    "dash.chart.hover": "Hover titik untuk detail",
    "dash.chart.total": "Total",
    "dash.chart.avg": "Rata-rata:",
    "dash.chart.peak": "Puncak:",
    "dash.chart.perday": "/ hari",
    "dash.chart.nodata": "Jalankan migration SQL untuk mengaktifkan analitik",
    "dash.export.csv": "Ekspor CSV",
    "dash.export.json": "Ekspor JSON",
    "dash.toppages": "Halaman Terpopuler",
    "dash.toppages.sub": "7 hari terakhir",
    "dash.stat.today": "Hari Ini",
    "dash.stat.week": "7 Hari",
    "dash.stat.projects": "Proyek",
    "dash.stat.portfolio": "Total portfolio",
    "dash.stat.top": "Top:",
    "dash.filter.7d": "7 Hari",
    "dash.filter.14d": "14 Hari",
    "dash.filter.30d": "30 Hari",
    "dash.time.justnow": "baru saja",
    "dash.time.minsago": "mnt lalu",
    "dash.time.hrsago": "jam lalu",
    "dash.time.daysago": "hari lalu",
    "dash.confirm.delete": "Hapus \"{title}\"? Tindakan ini tidak dapat dibatalkan.",
    "dash.deleting": "Menghapus...",
    "dash.portfolio.section": "Portofolio",
    "dash.portfolio.add": "Tambah Proyek",
    "dash.portfolio.subtitle": "Kelola semua proyek portofolio",
    "dash.portfolio.empty.title": "Belum ada proyek",
    "dash.portfolio.empty.desc": "Tambah proyek pertama kamu",
    "dash.portfolio.col.title": "Judul",
    "dash.portfolio.col.type": "Tipe",
    "dash.portfolio.col.year": "Tahun",
    "dash.portfolio.col.actions": "Aksi",
    "dash.portfolio.export": "Ekspor Proyek",
    "dash.portfolio.view": "Lihat halaman",

    // Settings
    "dash.settings.title": "Pengaturan",
    "dash.settings.subtitle": "Kelola kredensial dan sesi login",
    "dash.settings.account": "Akun Aktif",
    "dash.settings.form.title": "Perbarui Kredensial",
    "dash.settings.form.desc": "Ubah username dan password. Kamu akan logout setelah menyimpan.",
    "dash.settings.current.pw": "Password Saat Ini",
    "dash.settings.new.username": "Username Baru",
    "dash.settings.new.pw": "Password Baru",
    "dash.settings.confirm.pw": "Konfirmasi Password",
    "dash.settings.save": "Simpan Perubahan",
    "dash.settings.saving": "Menyimpan…",
    "dash.settings.saved": "Tersimpan — mengarahkan ke login…",
    "dash.settings.err.username": "Username minimal 3 karakter.",
    "dash.settings.err.pwlen": "Password baru minimal 4 karakter.",
    "dash.settings.err.pwmatch": "Password baru dan konfirmasi tidak cocok.",
    "dash.settings.err.network": "Koneksi gagal. Coba lagi.",
    "dash.settings.sessions": "Sesi Login Aktif",
    "dash.settings.sessions.revoke": "Cabut",
    "dash.settings.sessions.revoke.all": "Cabut {n} sesi lain",
    "dash.settings.sessions.none": "Tidak ada sesi aktif ditemukan.",
    "dash.settings.sessions.current": "Sesi ini",
    "dash.settings.sessions.footer": "Sesi yang dicabut akan logout otomatis pada permintaan berikutnya.",
    "dash.settings.sessions.expired": "kedaluwarsa",
    "dash.settings.sessions.expiry.days": "kedaluwarsa {d}h {h}j lagi",
    "dash.settings.sessions.expiry.hrs": "kedaluwarsa {h}j lagi",
    "dash.settings.sessions.login": "Login",
    "dash.settings.pw.weak": "Lemah",
    "dash.settings.pw.fair": "Cukup",
    "dash.settings.pw.strong": "Kuat",
    "dash.settings.pw.vstrong": "Sangat Kuat",

    // Sidenav
    "dash.nav.dashboard":   "Dashboard",
    "dash.nav.portfolio":   "Portofolio",
    "dash.nav.settings":    "Pengaturan",
    "dash.sidenav.viewsite":  "Lihat Site",
    "dash.sidenav.lightmode": "Mode Terang",
    "dash.sidenav.darkmode":  "Mode Gelap",
    "dash.sidenav.language":  "Bahasa",
    "dash.sidenav.logout":    "Keluar",
    "dash.sidenav.admin":     "Administrator",
    "dash.sidenav.expand":    "Perluas sidebar",
    "dash.sidenav.collapse":  "Ciutkan sidebar",

    // Stat / chart extras
    "dash.stat.totalviews":    "Total Tampilan",
    "dash.chart.updated":      "Diperbarui",
    "dash.novisit":            "Belum ada data kunjungan",

    // Actions
    "dash.actions.edit":    "Edit",
    "dash.actions.delete":  "Hapus",
    "dash.portfolio.manage": "Kelola",

    // ProjectForm — section type labels
    "form.stype.nutshell":          "In a Nutshell",
    "form.stype.context":           "Context",
    "form.stype.problem-discovery": "Problem Discovery",
    "form.stype.problem":           "Problem",
    "form.stype.solution":          "Solution",
    "form.stype.finaldesign":       "Final Design",
    "form.stype.reflection":        "Reflection",
    "form.stype.notion-only":       "Notion Only",

    // ProjectForm — UI strings
    "form.untitled":              "Tanpa judul",
    "form.section.type":          "Tipe Section",
    "form.section.content":       "Konten / Body Text",
    "form.section.image":         "Gambar (path)",
    "form.section.image.hint":    "Contoh: /Aitiserve_Context.jpg",
    "form.section.boldlist":      "Bold List (Context)",
    "form.section.add.item":      "Tambah Item",
    "form.section.design.items":  "Design Items (label + gambar)",
    "form.section.add.image":     "Tambah Gambar",
    "form.section.learnings":     "Learnings (satu per baris)",
    "form.section.collabs":       "Collaborators (satu per baris)",
    "form.section.add":           "Tambah Section",
    "form.section.empty":         "Belum ada section. Tambah section pertama.",

    "form.add.title":             "Tambah Proyek Baru",
    "form.edit.prefix":           "Edit:",
    "form.add.hint":              "Isi semua field lalu simpan",
    "form.saved":                 "✓ Tersimpan",
    "form.view":                  "Lihat →",
    "form.saving":                "Menyimpan…",
    "form.save":                  "Simpan",
    "form.err.save":              "Terjadi kesalahan saat menyimpan.",
    "form.err.network":           "Koneksi gagal. Coba lagi.",

    "form.card.identity":         "Identitas Proyek",
    "form.card.sections":         "Sections",
    "form.card.details":          "Detail Proyek",
    "form.card.tags":             "Tags & Skills",
    "form.card.visual":           "Visual & Links",

    "form.field.id":              "ID (slug unik)",
    "form.field.id.hint.new":     "Auto-generate dari judul",
    "form.field.id.hint.edit":    "Tidak bisa diubah setelah disimpan",
    "form.field.type":            "Tipe",
    "form.field.title":           "Judul",
    "form.field.desc":            "Deskripsi Singkat",
    "form.field.year":            "Tahun",
    "form.field.duration":        "Durasi",
    "form.field.role":            "Role",
    "form.field.client":          "Klien",
    "form.field.tags":            "Tags",
    "form.field.skills":          "Skills",
    "form.field.comma.hint":      "Pisahkan dengan koma",
    "form.field.bg.color":        "Warna Latar (hex)",
    "form.field.accent.color":    "Warna Aksen (hex)",
    "form.field.thumbnail":       "Thumbnail",
    "form.field.thumbnail.hint":  "Path dari /public",
    "form.field.liveurl":         "Live URL",
    "form.field.external":        "External Link (Notion)",
    "form.field.label.nav":       "Label (sidebar nav)",
    "form.field.heading":         "Heading",

    "form.ph.title":              "Judul proyek...",
    "form.ph.desc":               "Deskripsi singkat proyek...",
    "form.ph.section.content":    "Teks isi section...",
    "form.ph.desc.item":          "Deskripsi",
    "form.ph.learnings":          "Satu poin per baris...",
  },
};

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
